dataset:
  num_classes: 2
  training:
    video_mp4_path: ./datasets/thumos14/validation/
    video_info_path: thumos_annotations/val_video_info.csv
    video_anno_path: thumos_annotations/val_Annotation_VAD.csv
    video_data_path: ./datasets/thumos14/validation_npy/
    abnormal_data_path: ./datasets/thumos14/abnormal/
    normal_data_path: ./datasets/thumos14/normal/
    clip_length: 256
    clip_stride: 30
    crop_size: 96
  testing:
    video_mp4_path: ./datasets/thumos14/test/
    video_info_path: thumos_annotations/test_video_info.csv
    video_anno_path: thumos_annotations/test_Annotation_ours.csv
    video_data_path: ./datasets/thumos14/test_npy/
    crop_size: 96
    clip_length: 256
    clip_stride: 128

ucf:
  num_classes: 2
  training:
    video_mp4_path: datasets/UCF-Crime
    video_data_path: datasets/UCF-Crime/train_npy
    video_info_path: UCF-Crime_annotations/ucf_train_info.csv
    video_anno_path: UCF-Crime_annotations/ucf_train_anno.csv
    partition_num: 6116
    clip_length: 256
    clip_stride: 30
    crop_size: 96
  testing:
    video_mp4_path: datasets/UCF-Crime
    video_data_path: datasets/UCF-Crime/test_npy
    video_anno_path: UCF-Crime_annotations/ucf_test_anno.txt
    video_info_path: UCF-Crime_annotations/ucf_test_info.csv
    crop_size: 96
    clip_length: 256
    clip_stride: 128
    output_path: ./output
    output_json: detection_results_UCF.json
model:
  in_channels: 3
  freeze_bn: true
  freeze_bn_affine: true
  backbone_model: ./models/i3d_models/rgb_imagenet.pt

training:
  batch_size: 2
  learning_rate: 1e-6
  weight_decay: 1e-3
  max_epoch: 16
  focal_loss: true
  checkpoint_path: ./models/ucf/
  random_seed: 2020
  confidence_margin: 5
  partition_num: 4682

testing:
  conf_thresh: 0.01
  top_k: 5000
  nms_thresh: 0.5
  nms_sigma: 0.5
  checkpoint_path_thumos14: ./models/thumos14/VAD-checkpoint-nrt:5-16.ckpt
  checkpoint_path_ucf: ./models/ucf/VAD-checkpoint-ucf:5-9.ckpt
  output_path: ./output
  output_json: detection_results_VAD_new.json