# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VAD2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QApplication,QMainWindow


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(652, 537)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 30, 341, 41))
        self.label.setObjectName("label")
        self.videoAddres = QtWidgets.QLineEdit(Form)
        self.videoAddres.setGeometry(QtCore.QRect(200, 80, 321, 21))
        self.videoAddres.setObjectName("videoAddres")
        self.outputAddres = QtWidgets.QLineEdit(Form)
        self.outputAddres.setGeometry(QtCore.QRect(200, 130, 321, 21))
        self.outputAddres.setObjectName("outputAddres")
        self.thresh = QtWidgets.QLineEdit(Form)
        self.thresh.setGeometry(QtCore.QRect(200, 180, 131, 21))
        self.thresh.setObjectName("thresh")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(39, 80, 151, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 180, 81, 20))
        self.label_4.setObjectName("label_4")
        self.continueButton = QtWidgets.QPushButton(Form)
        self.continueButton.setGeometry(QtCore.QRect(500, 440, 113, 32))
        self.continueButton.setObjectName("continueButton")
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(380, 440, 113, 32))
        self.exitButton.setObjectName("exitButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(200, 230, 321, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 230, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(340, 180, 81, 20))
        self.label_7.setObjectName("label_7")
        self.thresh_2 = QtWidgets.QLineEdit(Form)
        self.thresh_2.setGeometry(QtCore.QRect(400, 180, 121, 21))
        self.thresh_2.setObjectName("thresh_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(100, 330, 81, 20))
        self.label_8.setObjectName("label_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(200, 330, 321, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "视频异常检测系统"))
        self.label.setText(_translate("Form", "欢迎使用视频异常检测系统,请在下方依次填写相关信息"))
        self.videoAddres.setText(_translate("Form", "sssssssssssssssssssssssssssssssssssssssssssssssssMyAlarm/Preview Content/video_test_0000050.mp4"))
        self.outputAddres.setText(_translate("Form", "TryOnMacosDev/MyAlarm/MyAlarm/Preview Content"))
        self.thresh.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "需要进行检测的视频地址"))
        self.label_3.setText(_translate("Form", "结果输出地址"))
        self.label_4.setText(_translate("Form", "异常分数阈值"))
        self.continueButton.setText(_translate("Form", "test"))
        self.exitButton.setText(_translate("Form", "exit"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">异常分数：5.78775787353156</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">类别：异常视频</p></body></html>"))
        self.label_5.setText(_translate("Form", "异常识别结果"))
        self.label_7.setText(_translate("Form", "IoU阈值"))
        self.thresh_2.setText(_translate("Form", "0.3"))
        self.label_8.setText(_translate("Form", "时序事件边界"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">起始时间：15.2</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">结束时间：18.4</p></body></html>"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())